# Generated by Django 2.1 on 2018-09-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersrecord',
            name='name',
            field=models.CharField(max_length=264),
        ),
    ]
